--
-- PostgreSQL database dump
--

-- Dumped from database version 17rc1
-- Dumped by pg_dump version 17rc1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: core_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_service (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(1000),
    base_price numeric(6,2) NOT NULL,
    picture character varying(100) NOT NULL,
    service_lengths jsonb NOT NULL
);


ALTER TABLE public.core_service OWNER TO postgres;

--
-- Name: core_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: core_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_service (id, name, description, base_price, picture, service_lengths) FROM stdin;
9	Facial Treatment	Indulge in our luxurious facial treatment that is meticulously designed to soothe and rejuvenate your skin.  This comprehensive experience begins with a thorough cleansing ritual, followed by toning and gentle exfoliation to prepare your face for the next steps. A soothing massage stimulates blood flow and encourages collagen production, while the carefully chosen mask and moisturizer, featuring all-natural products, work to nourish and hydrate your skin.  This facial treatment utilizes best-practice anti-aging techniques, ensuring that each session not only enhances your complexion but also promotes a refreshed and revitalized appearance.  Experience the ultimate in skincare and emerge with a glowing, youthful visage.	90.00	service_pictures/facial_treatment.png	[["60", 90], ["90", 130], ["120", 170]]
3	Deep Tissue Massage	Stress-relieving massage technique to alleviate tension and pain in the body by targeting the deeper layers of muscle and connective tissue.  During the session, the massage therapist skillfully employs their fingers, knuckles, and elbows to release muscle tension, enhancing flexibility and promoting overall relaxation.  This type of massage is particularly beneficial for athletes seeking to improve their performance, recover from injuries, or prevent future injuries. By focusing on the deeper muscle layers, these techniques not only assist in recovery but also contribute to optimal physical condition, ensuring that athletes can push their limits while maintaining their well-being.  Whether you're looking to unwind after a demanding workout or address specific pain points, this massage offers an effective solution for enhancing both physical and mental health.	95.00	service_pictures/deep_tissue_massage.png	[["60", 95], ["90", 140], ["120", 180]]
4	Slimming Massage	Slimming massage is an effective approach designed to enhance body contouring through the application of natural slimming creams combined with expert massage techniques.  Targeting specific problem areas such as the stomach, hips, and thighs, this specialized treatment helps diminish the visibility of cellulite. The therapist employs deep kneading and rolling motions, which not only enhance blood circulation but also aid in breaking down stubborn fatty deposits.  As a result, the skin appears firmer and more toned. Beyond its cosmetic benefits, slimming massage can support weight loss efforts and contribute to an overall improved skin appearance, making it a popular choice for those seeking to achieve their body goals in a holistic manner.	100.00	service_pictures/slimming_massage.png	[["60", 100], ["90", 140], ["120", 180]]
2	Relaxing Oil Massage	Experience the ultimate relaxation with our Swedish massage techniques, designed to soothe and energize your body.  Our skilled massage therapists will tailor each session to your individual needs, utilizing a harmonious combination of long strokes, kneading, and friction.  You have the option to enhance your experience with therapeutic oil or soothing aloe vera, ensuring optimal comfort and relief. Whether you seek a full-body massage or prefer to focus on specific areas such as your feet, back, shoulders, or head, we are committed to providing you with a personalized treatment that leaves you feeling rejuvenated and balanced.  Indulge in a moment of tranquility and let the stress of the day melt away.	80.00	service_pictures/relaxing_oil_massage.png	[["60", 80], ["90", 115], ["120", 150]]
5	Jet Lag Recovery Massage	Shake off travel fatigue and revive your body with our 90-minute Jet Lag Recovery Massage. Designed to help you adjust after long flights, this specialized treatment combines soothing techniques with relaxing herbal oils, focusing on the feet, legs, and lower back—areas most affected by prolonged sitting during travel. By easing tension in these key muscle groups and improving circulation, this massage restores your body’s natural rhythm and relieves discomfort.  Whether you're just arriving in Thailand or looking to reset after a journey, you'll feel refreshed, balanced, and ready to embrace the day with renewed energy.  Let us take care of you from the moment arrive, offering the perfect way to start your stay in complete comfort.	90.00	service_pictures/jet_lag_recovery_massage.png	[["60", 90], ["90", 130], ["120", 170]]
8	Foot Massage	Treat your feet to the care they deserve with our soothing foot massage. This rejuvenating treatment focuses on relieving tension and fatigue in your feet and lower legs, promoting circulation and overall relaxation. Using expert techniques, your therapist will apply gentle to firm pressure on key reflex points, helping to release stress and restore balance throughout your body.  Perfect for anyone who spends long hours on their feet or just needs a break from daily stress. Experience the revitalizing benefits of a foot massage today and feel the difference from the ground up.	70.00	service_pictures/foot_massage.png	[["60", 70], ["90", 100], ["120", 130]]
7	Pregnancy Massage	Nurture your body and ease the discomforts of pregnancy with our gentle and relaxing Pregnancy Massage, specifically designed for expectant mothers in their second trimester. During this period, many women experience muscle tension and discomfort, particularly in the back, shoulders, legs, and feet. This massage focuses on alleviating these common aches and providing a sense of comfort and relaxation.  Using soft, soothing strokes and safe, pregnancy-friendly oils, our skilled therapists apply specialized prenatal massage techniques that help reduce swelling, improve circulation, and relieve muscle tightness. This treatment promotes overall well-being for both mother and baby, allowing you to relax and enjoy this special time.  Experience the perfect balance of care and relaxation with a Pregnancy Massage, tailored to support you as you navigate this exciting chapter of your life.  Important: Please note that we offer Pregnancy Massage only for expectant mothers in their second trimest	85.00	service_pictures/pregnancy_massage.png	[["60", 85], ["90", 120], ["120", 150]]
10	Body Scrub	Indulge in a transformative experience with our skilled therapist, who will expertly apply an exotic blend of natural ingredients to gently exfoliate and remove dead skin.  This luxurious treatment will leave you with a refreshed and rejuvenated complexion, enhancing your natural glow. After the exfoliation, a soothing shower will wash away the scrub ingredients, ensuring a clean slate for the final touch. To complete your pampering session, choose from a selection of rich oils or moisturizers that will envelop your skin in nourishment. The result is skin that feels soft, smooth, and utterly revitalized, allowing you to embrace the day with confidence and radiance.  Treat yourself to this indulgent ritual and experience the delightful transformation firsthand.	80.00	service_pictures/body_scrub.png	[["60", 80], ["90", 110], ["120", 140]]
12	Manicure	Treat yourself to a professional manicure that will leave your hands looking exquisite.  Our skilled technician will expertly shape your nails and buffing them to perfection, ensuring a smooth and flawless finish. With every detail attended to, you can relax and enjoy the pampering experience. Your hands deserve this special treatment, so come and experience the difference today!  For those looking to add a unique touch, we offer the option to choose an extra gel and polish, allowing you to customize your nails with an extra pop of style.	50.00	service_pictures/manicure.png	[["60", 50], ["90", 70], ["120", 90]]
11	Foot Scrub	Indulge your feet with an invigorating foot scrub. Our skilled therapist will apply a specially formulated scrub that gently exfoliates and removes dead skin, ensuring your feet feel revitalized.  The treatment encompasses a thorough scrub of both the feet and toes, meticulously targeting every area for a complete cleanse. Following this refreshing exfoliation, a hydrating moisturizing treatment is applied to nourish and hydrate your skin deeply. This luxurious service guarantees that your feet will emerge feeling smooth, refreshed, and rejuvenated, ready to take on the world.  Treat yourself to this indulgent experience and discover the joy of beautifully cared-for feet.	40.00	service_pictures/foot_scrub.png	[["60", 40], ["90", 60], ["120", 80]]
13	Pedicure	Indulge in a moment of relaxation by treating your feet to our professional pedicure service.  Our skilled technician will meticulously shape your nails, buff them to a smooth finish, and apply a perfect polish that enhances your natural beauty. Whether you're preparing for a special occasion or simply want to unwind, this pampering experience is designed to leave your feet looking and feeling fabulous. Step out with confidence and show off your beautifully cared-for feet!  For those looking to elevate their pedicure even further, you have the option to choose an extra gel that adds a stunning touch of style to your nails.	60.00	service_pictures/pedicure.png	[["60", 60], ["90", 80], ["120", 100]]
14	Yoga Personal Training	Enhance your strength, flexibility, and overall well-being with our personalized yoga training.  Our certified yoga instructors provide individualized attention in one-on-one sessions or small groups of up to three participants, ensuring that your practice is tailored to your unique needs and fitness goals. Whether you are a beginner or an experienced yogi, each session will include a customized sequence of poses, breathing exercises, and meditation. This approach not only boosts your physical strength and flexibility but also helps in reducing stress and promoting relaxation.  Start your journey towards better health and mindfulness today with our dedicated yoga training.   If you wish to join larger groups, please note that an additional fee of ฿500 per person will apply.	85.00	service_pictures/yoga_personal_training.png	[["60", 85], ["90", 120], ["120", 150]]
1	Thai Massage	Traditional ancient Thai massage, practiced by monks for centuries, is a holistic approach to healing that incorporates a unique blend of techniques using palms, thumbs, and elbows. This therapeutic form of massage targets deep pressure points to alleviate tension throughout the body, promoting relaxation and rejuvenation.  The combination of stretches and focused pressure not only helps restore the body’s natural 'chi' energy but also enhances mobility and flexibility.  This massage is designed to leave you feeling relaxed and rejuvenated, with a renewed sense of well-being.  This age-old practice embodies the principles of harmony and peace, making it a cherished approach to physical and mental wellness in Thai culture.	70.00	service_pictures/thai_massage.png	[["60", 70], ["90", 100], ["120", 130]]
6	Myofascial Massage	Myofascial massage, often referred to as office syndrome massage, is a specialized therapeutic technique designed to target the body's connective tissue, known as fascia.  This type of massage is particularly effective for alleviating pain, stiffness, and tension that arise from repetitive movements, long hours of sitting, or poor posture. Individuals suffering from office syndrome find relief through this massage, as it enhances their range of motion and overall well-being.  The therapist employs specific manipulation techniques to release tension within the fascia, promoting proper movement and function in the affected areas. As a result, patients will experience improved comfort and a greater sense of vitality, making myofascial massage a valuable option for those seeking recovery from the stresses of modern work life.	90.00	service_pictures/myofascial_massage.png	[["60", 90], ["90", 130], ["120", 170]]
\.


--
-- Name: core_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_service_id_seq', 14, true);


--
-- Name: core_service core_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_service
    ADD CONSTRAINT core_service_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

