# Generated by Django 5.1.4 on 2025-01-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCustomerGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple'), ('group', 'Group')], max_length=30)),
            ],
            options={
                'verbose_name': 'Accepted Customer Group',
                'verbose_name_plural': 'Accepted Customer Groups',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prices', models.JSONField(default=list)),
                ('picture', models.ImageField(upload_to='service_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_customers', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('booking_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prices', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='customers.customer')),
            ],
        ),
    ]
