# Generated by Django 5.1.3 on 2024-11-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='therapists.therapistservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='therapists.therapist'),
        ),
    ]
