# Generated by Django 5.1.4 on 2025-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
