# Generated by Django 5.1.4 on 2025-01-27

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        # 1. Add 'city' to Booking
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),

        # 3. Alter 'service' field in Booking
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='booking',
                to='core.service'
            ),
        ),
    ]
