# Generated by Django 5.1.3 on 2024-11-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='therapist_id',
            new_name='therapist',
        ),
    ]
