# Generated by Django 5.1.3 on 2024-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_customer_id_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_customers',
            field=models.CharField(choices=[('one', 'One'), ('couple', 'Couple'), ('group', 'Group')], max_length=30),
        ),
    ]
