# Generated by Django 5.1.4 on 2025-01-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_types',
            field=models.ManyToManyField(related_name='services', to='core.servicetype'),
        ),
    ]
