# Generated by Django 5.1.4 on 2025-01-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment_datetime',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.booking'),
            preserve_default=False,
        ),
    ]
