# Generated by Django 5.1.3 on 2024-12-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_number_of_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple'), ('group', 'Group')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='meuh', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_customers',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_customers',
            field=models.ManyToManyField(to='core.numberofcustomers'),
        ),
    ]
