# Generated by Django 5.1.4 on 2025-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Berlin', max_length=255),
            preserve_default=False,
        ),
    ]
