# Generated by Django 5.1.1 on 2025-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_numberofcustomers_booking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
