# Generated by Django 5.1.4 on 2025-01-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='city',
        ),
    ]
