# Generated by Django 5.1.4 on 2025-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notification_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_types',
            field=models.ManyToManyField(related_name='services', to='core.servicetype'),
        ),
    ]
