# Generated by Django 5.1.1 on 2025-01-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicetype_remove_service_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_lengths',
            field=models.JSONField(default=list),
        ),
    ]
