# Generated by Django 5.1.4 on 2025-01-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_service_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='taken',
        ),
    ]
