# Generated by Django 5.1.4 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_customers',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_customers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
