# Generated by Django 5.1.4 on 2025-01-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_booking_number_of_customers_and_more'),
        ('therapists', '0006_remove_therapist_number_of_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberOfCustomers',
            new_name='AcceptedNumberOfCustomers',
        ),
    ]
