# Generated by Django 5.1.4 on 2025-01-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_numberofcustomers_acceptednumberofcustomers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedNumberOfCustomers',
            new_name='AcceptedCustomerGroups',
        ),
        migrations.AlterModelOptions(
            name='acceptedcustomergroups',
            options={'verbose_name': 'Accepted Customer Group', 'verbose_name_plural': 'Accepted Customer Groups'},
        ),
    ]
