# Generated by Django 5.1.4 on 2025-01-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_service'),
        ('therapists', '0013_rename_address_therapist_street_therapist_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='therapists.therapistservice'),
        ),
    ]
