# Generated by Django 5.1.4 on 2025-01-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_status'),
        ('core', '0015_rename_service_lengths_service_prices_and_more'),
    ]

    operations = [
    ]
