# Generated by Django 5.1.3 on 2024-11-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Man'), ('O', 'Other')], max_length=1)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='therapist_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_services', to='core.service')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='therapists.therapist')),
            ],
        ),
    ]
