# Generated by Django 5.1.3 on 2024-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='equipment_pref',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='number_of_customers',
            field=models.CharField(choices=[('one', 'One'), ('couple', 'Couple'), ('group', 'Group')], default='one', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='specialties',
            field=models.CharField(default='feet', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='years_xp',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
