# Generated by Django 5.1.4 on 2025-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='pronouns',
            field=models.CharField(blank=True, default='Not Specified', max_length=50, null=True),
        ),
    ]
