# Generated by Django 5.1.3 on 2024-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_therapist_equipment_pref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='picture',
            field=models.ImageField(default='picture.jpg', upload_to='therapist_pictures/'),
            preserve_default=False,
        ),
    ]
