# Generated by Django 5.1.3 on 2024-12-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_numberofcustomers_booking_address_and_more'),
        ('therapists', '0003_alter_therapist_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='qualifications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='number_of_customers',
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialties',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_org', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('certif_file', models.FileField(upload_to='uploads/')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='therapists.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='therapist',
            name='number_of_customers',
            field=models.ManyToManyField(to='core.numberofcustomers'),
        ),
    ]
