# Generated by Django 5.1.4 on 2025-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_therapist_address_therapist_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='number_of_customers',
        ),
        migrations.AddField(
            model_name='therapist',
            name='number_of_customers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
