# Generated by Django 5.1.4 on 2025-01-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0005_remove_therapist_number_of_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='number_of_customers',
        ),
    ]
