# Generated by Django 5.1.4 on 2025-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_numberofcustomers_acceptednumberofcustomers'),
        ('therapists', '0006_remove_therapist_number_of_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='accepted_number_of_customers',
            field=models.ManyToManyField(blank=True, to='core.acceptednumberofcustomers'),
        ),
    ]
