# Generated by Django 5.1.4 on 2025-01-16 14:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0007_therapist_accepted_number_of_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='accepted_number_of_customers',
        ),
        migrations.AddField(
            model_name='therapist',
            name='accepted_number_of_customers',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('single', 'Single'), ('couple', 'Couple'), ('group', 'Group')], max_length=19),
        ),
    ]
