# Generated by Django 5.1.4 on 2025-01-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0008_remove_therapist_accepted_number_of_customers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='accepted_number_of_customers',
            new_name='accepted_customer_groups',
        ),
    ]
