# Generated by Django 5.1.4 on 2025-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0009_rename_accepted_number_of_customers_therapist_accepted_customer_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='equipment_pref',
            new_name='provided_equipment',
        ),
        migrations.AddField(
            model_name='therapist',
            name='required_equipment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
