# Generated by Django 5.1.4 on 2025-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0010_rename_equipment_pref_therapist_provided_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='pronouns',
            field=models.CharField(choices=[('she/her', 'She/Her'), ('he/him', 'He/Him'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
