# Generated by Django 5.1.4 on 2025-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0012_remove_therapist_name_therapist_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='therapist',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
