# Generated by Django 5.1.4 on 2025-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0013_rename_address_therapist_street_therapist_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistservice',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='therapistservice',
            name='prices',
            field=models.JSONField(default=list),
        ),
    ]
