# Generated by Django 5.1.4 on 2025-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0014_rename_price_therapistservice_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistservice',
            name='picture',
            field=models.ImageField(default='body_scrub.png', upload_to='service_pictures/'),
            preserve_default=False,
        ),
    ]
