# Generated by Django 5.1.4 on 2025-01-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0015_therapistservice_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistservice',
            name='picture',
        ),
        migrations.AlterField(
            model_name='therapistservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=6),
        ),
    ]
