# Generated by Django 5.1.4 on 2025-01-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0015_therapistservice_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistservice',
            name='picture',
        ),
    ]
