# Generated by Django 5.1.4 on 2025-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0016_remove_therapistservice_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('she/her', 'She/Her'), ('he/him', 'He/Him'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
